/**
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.formatting2;

import com.google.inject.Inject;
import fr.n7.petriNet.txt.services.NETGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import petrinet.Arc;
import petrinet.Element;
import petrinet.Network;

@SuppressWarnings("all")
public class NETFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private NETGrammarAccess _nETGrammarAccess;

  protected void _format(final Network network, @Extension final IFormattableDocument document) {
    EList<Element> _elements = network.getElements();
    for (final Element element : _elements) {
      document.<Element>format(element);
    }
    EList<Arc> _arcs = network.getArcs();
    for (final Arc arc : _arcs) {
      document.<Arc>format(arc);
    }
  }

  public void format(final Object network, final IFormattableDocument document) {
    if (network instanceof XtextResource) {
      _format((XtextResource)network, document);
      return;
    } else if (network instanceof Network) {
      _format((Network)network, document);
      return;
    } else if (network instanceof EObject) {
      _format((EObject)network, document);
      return;
    } else if (network == null) {
      _format((Void)null, document);
      return;
    } else if (network != null) {
      _format(network, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(network, document).toString());
    }
  }
}
