/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NETUiModule extends AbstractNETUiModule {

	public NETUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
