/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NETAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/n7/petriNet/txt/parser/antlr/internal/InternalNET.tokens");
	}
}
