/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.parser.antlr;

import com.google.inject.Inject;
import fr.n7.petriNet.txt.parser.antlr.internal.InternalNETParser;
import fr.n7.petriNet.txt.services.NETGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class NETParser extends AbstractAntlrParser {

	@Inject
	private NETGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNETParser createParser(XtextTokenStream stream) {
		return new InternalNETParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Network";
	}

	public NETGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NETGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
