/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractNETScopeProvider extends DelegatingScopeProvider {
}
