/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.petriNet.txt.NETRuntimeModule;
import fr.n7.petriNet.txt.NETStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class NETIdeSetup extends NETStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new NETRuntimeModule(), new NETIdeModule()));
	}
	
}
