/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NETStandaloneSetup extends NETStandaloneSetupGenerated {

	public static void doSetup() {
		new NETStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
