/*
 * generated by Xtext 2.29.0
 */
package fr.n7.petriNet.txt.ui;

import com.google.inject.Injector;
import fr.n7.petriNet.txt.net.ui.internal.NetActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NETExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(NetActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		NetActivator activator = NetActivator.getInstance();
		return activator != null ? activator.getInjector(NetActivator.FR_N7_PETRINET_TXT_NET) : null;
	}

}
